services:
  - type: web
    name: elearning-platform
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Set in Render dashboard
    autoDeploy: true
